version: '3'
services:
  api:
    image: 'node:latest'
    working_dir: /api
    ports:
      - 3000:3000
    environment: 
      - PORT=3000
      - PGUSER=neifors
      - PGHOST=db
      - PGPASSWORD=neiforspass
      - PGDATABASE=michaeljackson
      - PGPORT=5432
    depends_on: 
      - db
    volumes:
      - type: bind
        source: ./
        target: /api
    command: bash -c "npm install && npm start"
  db:
    image: 'postgres:11.1'
    expose:
      - "5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "./db/:/docker-entrypoint-initdb.d/:ro"
    environment: 
      - POSTGRES_DB=michaeljackson
      - POSTGRES_USER=neifors
      - POSTGRES_PASSWORD=neiforspass
volumes:
  dbdata:
